version: 2
jobs:
  build:
    working_directory: ~/project
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docksal
          command: curl -fsSL get.docksal.io | bash
      - run:
          name: Fin Version
          command: fin --version
#       - setup_remote_docker:
#           version: '18.09.0'
#       - run:
#           name: Install Docker client
#           command: |
#             set -x
#             VER="18.09.2-ce"
#             curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
#             tar -xz -C /tmp -f /tmp/docker-$VER.tgz
#             mv /tmp/docker/* /usr/bin
#       - run:
#           name: Install Docker Compose
#           command: |
#             set -x
#             VER="1.23.2"
#             curl -L https://github.com/docker/compose/releases/download/$VER/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#             chmod +x ~/docker-compose
#             sudo mv ~/docker-compose /usr/local/bin/docker-compose
