version: 2
jobs:
  build:
    working_directory: /var/www
    docker:
      - image: busybox
      - image: docksal/cli:2-php7.2
        command: [supervisord]
      - image: docksal/mysql:5.6-1.4
        command: [mysqld]
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_ALLOW_EMPTY_PASSWORD=0
          - MYSQL_RANDOM_ROOT_PASSWORD=0
      - image: docksal/apache:2.4-2.3
        command: [httpd-foreground]
    steps:
      - run: rm -rf /var/www
      - checkout
#       - setup_remote_docker:
#           version: '18.09.0'
#       - run:
#           name: Install Docker client
#           command: |
#             set -x
#             VER="18.09.2-ce"
#             curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
#             tar -xz -C /tmp -f /tmp/docker-$VER.tgz
#             mv /tmp/docker/* /usr/bin
#       - run:
#           name: Install Docker Compose
#           command: |
#             set -x
#             VER="1.23.2"
#             curl -L https://github.com/docker/compose/releases/download/$VER/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#             chmod +x ~/docker-compose
#             sudo mv ~/docker-compose /usr/local/bin/docker-compose
